version: "3"
services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"

  nats:
    image: nats:2.1.9
    ports:
      - "6222:6222"
      - "4222:4222"
      - "8222:8222"

  redis:
    image: redis:6.0.9
    ports:
      - "6379:6379"

  service:
    image: ${AWS_ECR_URL}/codenames_service
    build:
      context: service
      dockerfile: Dockerfile.local
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    depends_on:
      - redis
    environment:
      - PORT=${SERVICE_PORT}
      - REDIS_HOST=redis
      - ALLOWED_ORIGINS=service-test,app,http://localhost:${APP_PORT},http://${HOST}:${APP_PORT}

  service-test:
    build:
      context: service
      dockerfile: Dockerfile.test
    depends_on:
      - service

  wash:
    build:
      context: service
      dockerfile: Dockerfile.wash
    depends_on:
      - nats
      - redis
      - registry
    environment:
      - WASH_RPC_HOST=nats
    ports:
      - "8080:8080"

  app:
    image: ${AWS_ECR_URL}/codenames_app
    build:
      context: app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - service
    environment:
      - PORT=${APP_PORT}
      - API_URL=http://${HOST}:${SERVICE_PORT}

