version: "3"
services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"

  nats:
    image: nats:2.1.9
    ports:
      - "6222:6222"
      - "4222:4222"
      - "8222:8222"

  redis:
    image: redis:6.0.9
    ports:
      - "6379:6379"

  service:
    build:
      context: service
      dockerfile: Dockerfile.local
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - ALLOWED_ORIGINS=service-test,app,http://localhost:3000

  service-test:
    build:
      context: service
      dockerfile: Dockerfile.test
    depends_on:
      - service

  wash:
    build:
      context: service
      dockerfile: Dockerfile.wash
    depends_on:
      - nats
      - redis
      - registry

  app:
    build:
      context: app
    ports:
      - "3000:3000"
    depends_on:
      - service
    environment:
      - API_URL=http://service:8080

