version: "3"
services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"

  nats:
    image: nats:2.1.9
    ports:
      - "6222:6222"
      - "4222:4222"
      - "8222:8222"

  redis:
    image: redis:6.0.9
    ports:
      - "6379:6379"

  service:
    image: ${AWS_ECR_URL}/codenames_service
    build:
      context: service
      dockerfile: Dockerfile.local
    ports:
      - ${SERVICE_PORT:-8080}:${SERVICE_PORT:-8080}
    depends_on:
      - redis
    environment:
      - PORT=${SERVICE_PORT:-8080}
      - REDIS_HOST=redis
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000}

  service-test:
    build:
      context: service
      dockerfile: Dockerfile.test
    depends_on:
      - service

  app:
    image: ${AWS_ECR_URL}/codenames_app
    build:
      context: app
    ports:
      - ${APP_PORT:-3000}:${APP_PORT:-3000}
    depends_on:
      - service
    environment:
      - PORT=${APP_PORT:-3000}
      - API_URL=${API_URL:-http://localhost:8080}

