FROM python:3.9.6-slim-buster

COPY Pipfile .
COPY Pipfile.lock .
COPY integration_tests.py .

RUN pip install pipenv
RUN pipenv install

ENV TEST_HOST service

ENTRYPOINT pipenv run pytest -v -s integration_tests.py
